project:
  type: book

book:
  title: "The Living Data Project: Data Rescue Guidebook"
  subtitle: "A guide to data rescue for Living Data Project interns and data rescue teams"
  author: "Members of the Living Data Project and DataStream"
  page-navigation: true
  
  repo-url: https://github.com/brcurrinder/ldp-data-rescue-guide
  repo-actions: [source, issue]


  chapters:
    - index.qmd

    - part: "Introduction to Data Rescue"
      chapters:
        - chapters/introduction.qmd
        - chapters/introduction-datastream.qmd
        - chapters/data.qmd
        - chapters/metadata.qmd
        - chapters/digitization.qmd
        - chapters/repositories-doi.qmd

    - part: "Open Science and Best Practices"
      chapters:
        - chapters/open-science-reproducible-research.qmd
        - chapters/coding-best-practices.qmd
        
    - part: "Artificial Intelligence"
      chapters:
        - chapters/ai-overview.qmd
        - chapters/ai-validation-example.qmd

    - part: "General Data Rescue Workflow"
      chapters:
        - chapters/getting-started.qmd
        - chapters/prepare-metadata.qmd
        - chapters/prepare-data.qmd
        - chapters/archiving-uploading.qmd
        
    - part: "DataStream Data Rescue Workflow"
      chapters:
        - chapters/prepare-metadata-datastream.qmd
        - chapters/prepare-data-datastream.qmd
        - chapters/uploading-datastream.qmd
        
    - part: "Additional Tasks"
      chapters:
        - chapters/internship_tasks.qmd
        - chapters/living_document.qmd
        
    - part: "Compiled References & Resources"
      chapters:
        - chapters/references.qmd
        - chapters/resources.qmd


format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    include-after-body: includes/tooltips.html