project:
  type: book

book:
  title: "LDP Data Rescue Guide"
  
  chapters:
    - index.qmd
    - chapters/getting-started.qmd
    - chapters/data-rescue-workflow.qmd
    - chapters/metadata.qmd
    - chapters/datastream.qmd
    - chapters/templates.qmd

format:
  html:
    theme: cosmo
    toc: true

